version: '2'
services:
  neo4j: 
    image: neo4j:3.4.7-enterprise
    volumes:
    - /opt/neo4j/data:/data
    ports:
    - 7474:7474
    - 7687:7687
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes" 
      NEO4J_AUTH: none 
        
  delivery-exercise:
    image: delivery-exercise:1.0.0
    environment:
      SPRING_DATA_NEO4J_URI: bolt://neo4j
      SPRING_DATA_NEO4J_USERNAME: neo4j
      SPRING_DATA_NEO4J_PASSWORD: neo4j
    ports:
    - 8080:8080
    links:
    - neo4j:neo4j

    